language: node_js
cache: yarn
node_js:
  - "lts/*"
  - "node"
install:
  - yarn install -D
  - yarn add webpack-subresource-integrity compression-webpack-plugin
script:
  - yarn run test
branches:
  except:
  - /poc-.*/
